name = "ModernRoboticsBook"
uuid = "d5dba9c0-6b5c-5258-ac1b-6bb6b2eb8086"
authors = ["Henrique Ferrolho <henriqueferrolho@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
